import test from 'node:test';
import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import {createServer, get} from 'node:http';
import {mkdtemp, rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join, resolve} from 'node:path';
import {once} from 'node:events';
import {DatabaseSync} from 'node:sqlite';

test('metadata-only apps survive model removal, enforce integrity, and never create app tables', {timeout: 90000}, async t => {
  const directory = await mkdtemp(join(tmpdir(), 'on-the-fly-'));
  let child, candidate, calls = 0, modelRequest, logs = '';
  const model = createServer(async (req, res) => {
    calls++; let text = ''; for await (const chunk of req) text += chunk;
    modelRequest = JSON.parse(text);
    res.setHeader('Content-Type', 'application/json');
    res.end(JSON.stringify({choices: [{message: {content: JSON.stringify(candidate)}}]}));
  });
  model.listen(0, '127.0.0.1'); await once(model, 'listening');
  const reserve = createServer(); reserve.listen(0, '127.0.0.1'); await once(reserve, 'listening');
  const port = reserve.address().port; await new Promise(done => reserve.close(done));
  const origin = `http://127.0.0.1:${port}`;
  async function stop() {if (child && child.exitCode === null) {const exited = once(child, 'exit'); child.kill('SIGTERM'); await exited;}}
  t.after(async () => {await stop(); await new Promise(done => model.close(done)); await rm(directory, {recursive: true, force: true});});
  async function start(connected) {
    const env = {...process.env, LLM_BASE_URL: connected ? `http://127.0.0.1:${model.address().port}/v1` : '', LLM_MODEL: connected ? 'integration-stub' : '', LLM_API_KEY: ''};
    child = spawn(resolve('.tools', process.platform === 'win32' ? 'pocketbase.exe' : 'pocketbase'), ['serve', `--http=127.0.0.1:${port}`, `--dir=${directory}`, '--hooksDir=pb_hooks', '--migrationsDir=pb_migrations', '--publicDir=pb_public', '--hooksWatch=false'], {env});
    child.stdout.on('data', chunk => {logs += chunk;}); child.stderr.on('data', chunk => {logs += chunk;});
    for (let i = 0; i < 150; i++) {try {const response = await fetch(origin + '/api/workspace/workspace/'); if (response.ok) return;} catch (_) {} await new Promise(done => setTimeout(done, 50));}
    throw Error('Server did not start: ' + logs);
  }
  async function request(action, method = 'GET', data, expected = 200) {
    const response = await fetch(`${origin}/api/workspace/${action}`, {method, headers: {'Content-Type': 'application/json', 'X-Workspace': '1'}, body: data === undefined ? undefined : JSON.stringify(data)});
    const json = await response.json();
    assert.equal(response.status, expected, JSON.stringify(json)); return json.data;
  }
  const tables = () => {const db = new DatabaseSync(join(directory, 'data.db'), {readOnly: true});
    const rows = db.prepare("SELECT name, sql FROM sqlite_master WHERE type='table' ORDER BY name").all();
    db.close();
    return rows;};
  await start(true);
  assert.equal((await request('workspace/')).version, 0);
  const initialTables = tables();
  await request('example/', 'POST', {});
  let state = await request('workspace/');
  assert.equal(state.version, 1); assert.equal(state.modelCalls, 0);
  assert.equal((await request('query/recent_sales')).total, 6);
  assert.equal((await request('query/sales_total')).value, 44600);
  assert.equal((await request('query/pipeline_total')).value, 120500);
  assert.equal((await request('query/opportunity_count')).value, 4);
  assert.equal((await request('query/pipeline_stages')).items.find(i => i.label === 'Proposal').value, 56000);
  const projected = await request('query/recent_sales?perPage=2&page=2&orderBy=amount&orderDir=asc');
  assert.equal(projected.items.length, 2); assert.equal(projected.total, 6); assert.equal(projected.items[0].amount, 6000);
  await request('record/', 'POST', {object: 'sales', data: {name: 'Invalid', amount: '12', date: '2026-02-30', status: 'Paid'}}, 400);
  await request('record/', 'POST', {object: 'companies', data: {name: 'Acme Studio'}}, 400);
  const company = (await request('query/_object_companies')).items[0];
  const sale = (await request('query/recent_sales')).items[0];
  await request('links/company_sales', 'POST', {source: sale.id, target: company.id}, 400);
  const originalLink = (await request('links/company_sales')).items[0];
  await request('links/company_sales', 'POST', {source: originalLink.source, target: originalLink.target}, 400);
  const other = (await request('query/_object_companies')).items.find(r => r.id !== originalLink.source);
  await request('links/company_sales', 'POST', {source: other.id, target: originalLink.target}, 400);
  const incompatible = structuredClone(state.config); incompatible.objects.find(o => o.id === 'sales').fields.find(f => f.id === 'amount').type = 'text';
  await request('workspace/', 'POST', {config: incompatible, version: 1}, 400);
  const injected = structuredClone(state.config); injected.screens[0].widgets[0].adaptor = 'alert(1)';
  await request('workspace/', 'POST', {config: injected, version: 1}, 400);
  const missing = structuredClone(state.config); missing.screens[0].widgets[0].query = 'missing';
  await request('workspace/', 'POST', {config: missing, version: 1}, 400);
  candidate = structuredClone(state.config); candidate.screens[0].title = 'My generated dashboard';
  candidate.queries.find(q => q.id === 'recent_sales').filters[0].value = 7;
  candidate.objects.push({id: 'tasks', label: 'Tasks', fields: [{id: 'name', label: 'Task', type: 'text', required: true, unique: true}, {id: 'done', label: 'Done', type: 'boolean'}]});
  candidate.relations.push({id: 'company_tasks', label: 'Company tasks', from: 'companies', to: 'tasks', cardinality: 'many-to-many'});
  const proposal = await request('generate/', 'POST', {prompt: 'Show sales for seven days and add tasks'});
  assert.equal(calls, 1); assert.equal(modelRequest.messages[1].content, 'Show sales for seven days and add tasks');
  assert.equal((await request('workspace/')).version, 1, 'Generation must not mutate active metadata');
  await request('workspace/', 'POST', {config: proposal.config, version: proposal.version});
  await request('workspace/', 'POST', {config: proposal.config, version: proposal.version}, 409);
  state = await request('workspace/'); assert.equal(state.version, 2); assert.equal(state.modelCalls, 1);
  assert.equal((await request('query/recent_sales')).total, 3);
  assert.deepEqual(tables(), initialTables, 'Virtual objects must not create or alter physical tables');
  const task = await request('record/', 'POST', {object: 'tasks', data: {name: '<img src=x onerror=alert(1)>', done: false}});
  await request(`record/${task.id}`, 'POST', {object: 'tasks', data: {name: 'Call Acme', done: true}});
  assert.equal((await request(`record/${task.id}`)).done, true);
  await request('links/company_tasks', 'POST', {source: company.id, target: task.id});
  await request('links/company_tasks', 'POST', {source: other.id === company.id ? originalLink.source : other.id, target: task.id});
  const related = structuredClone(state.config);
  related.queries.push({id: 'tasks_for_company', object: 'tasks', fields: ['name'], filters: [], aggregate: 'rows', related: {relation: 'company_tasks', record: company.id}});
  await request('workspace/', 'POST', {config: related, version: 2});
  assert.equal((await request('query/tasks_for_company')).items[0].name, 'Call Acme');
  await request(`record/${company.id}`, 'DELETE', undefined, 400);
  const parallel = await Promise.all(['POST', 'POST'].map(method => fetch(origin + '/api/workspace/record/', {method, headers: {'Content-Type': 'application/json', 'X-Workspace': '1'}, body: JSON.stringify({object: 'tasks', data: {name: 'Unique concurrent task'}})})));
  assert.deepEqual(parallel.map(r => r.status).sort(), [200, 400]);
  candidate = {screens: [{type: 'javascript'}]};
  await request('generate/', 'POST', {prompt: 'Invalid metadata from model'}, 400);
  assert.equal((await request('workspace/')).version, 3);
  assert.equal((await fetch(origin + '/api/collections/records/records')).status, 403);
  assert.equal((await fetch(origin + '/api/workspace/workspace/', {method: 'POST', body: '{}', headers: {'Content-Type': 'application/json'}})).status, 403);
  assert.equal((await fetch(origin + '/api/workspace/workspace/', {headers: {Origin: 'https://untrusted.example'}})).status, 403);
  const hostileHostStatus = await new Promise(done => get(origin + '/api/workspace/workspace/', {headers: {Host: 'untrusted.example'}}, res => {res.resume();
    done(res.statusCode);}));
  assert.equal(hostileHostStatus, 403);
  await stop(); await start(false);
  state = await request('workspace/'); assert.equal(state.modelReady, false); assert.equal(state.version, 3);
  assert.equal(state.config.screens[0].title, 'My generated dashboard');
  assert.equal((await request('query/recent_sales')).total, 3);
  await request(`record/${task.id}`, 'DELETE'); assert.equal((await request('links/company_tasks')).items.length, 0);
  await request('generate/', 'POST', {prompt: 'No model is available'}, 400);
  assert.equal((await request('workspace/')).modelCalls, 0);
  assert.equal(calls, 2, 'All saved views and CRUD must run without another provider call');
  const restored = await request('revision/1');
  await request('workspace/', 'POST', {config: restored, version: 3}, 400); // Existing task data prevents destructive rollback.
  const taskRows = await request('query/_object_tasks');
  for (const item of taskRows.items) await request(`record/${item.id}`, 'DELETE');
  await request('workspace/', 'POST', {config: restored, version: 3});
  assert.equal((await request('workspace/')).version, 4);
  assert.equal((await request('query/recent_sales')).total, 6);
  assert.deepEqual(tables(), initialTables);
});
